In [22]:
#выражение, которое пытаемся максимизировать
#Y = sigma(w1x1 + w2x2 + w3x3 + w4x4 + w5x5 + w6x6)
#(x1,x2,x3,x4,x5,x6)=(4,-2 ,7, 5,-11, 1) - такие иксы
# пытаемся подобрать w такие, чтобы Y был максимаьным
#
#
#

In [23]:
import math

def sigmoid(x):
    return 1 / (1 + math.exp(-x))

In [24]:
# входные данные
equation_inputs = [4, -2, 7, 5, -11, 1]
# количество весов
num_weights = len(equation_inputs)

In [25]:
import numpy as np

sol_per_pop = 8  # определяем, сколько решений будет у первой "популяции"

pop_size = (sol_per_pop, num_weights) # таков размер первой популяции.

#создаем первую популяцию случайно.
new_population = np.random.uniform(low=-4.0, high=4.0, size=pop_size)
for elem in new_population:
    print(elem)

[ 3.75694105 -2.50868406 -1.5219798  -2.94725832 -3.6209088   1.52725613]
[-1.184223    1.06372314 -1.42789017  3.38479639 -0.71010723  0.73635779]
[-2.17272739 -2.09445354 -1.16801608  1.37012403  2.80079893 -0.94583159]
[-0.45938165 -2.03939125 -2.5813193  -0.82911337  0.98616039 -1.46929516]
[ 0.30262367 -3.32763182 -3.99506651 -1.21905473  2.15537218  0.88985555]
[-1.92673497  2.71814584 -0.50903058 -2.69108552 -0.93086091  1.68742579]
[-1.1376357   0.05775645 -1.37039708 -0.08728147  3.30636144 -3.66398176]
[ 2.9781703   3.62579471 -2.6878584  -3.38904473 -1.12441799 -1.47066511]


In [40]:
# функция для посчета, насколько ответ подходящий (просто считаем У)
def cal_pop_fitness(equation_inputs, pop):
    fitness = sigmoid(np.sum(pop*equation_inputs, axis=1))
    return fitness


def select_mating_pool(pop, fitness, num_parents):
    #выбираем наилучших "родителей" в популяции
    parents = np.empty((num_parents, pop.shape[1]))
    for parent_num in range(num_parents):
        max_fitness_idx = np.where(fitness == np.max(fitness))
        max_fitness_idx = max_fitness_idx[0][0]
        parents[parent_num, :] = pop[max_fitness_idx, :]
        fitness[max_fitness_idx] = -99999999999
    return parents


def crossover(parents, offspring_size):
    offspring = np.empty(offspring_size)
    # Точка, в которой появляется кроссовер 
    crossover_point = np.uint8(offspring_size[1]/2)
    for k in range(offspring_size[0]):
     #индекс перого родителя
     parent1_idx = k%parents.shape[0]
     #индекс второго родителя
     parent2_idx = (k+1)%parents.shape[0]
     #половину "генов" берем от одного родителя
     offspring[k, 0:crossover_point] = parents[parent1_idx, 0:crossover_point]
     #половину "генов" берем от второго родителя
     offspring[k, crossover_point:] = parents[parent2_idx, crossover_point:]
    return offspring


def mutation(offspring_crossover):
    # Мутация изменят "гены" случайно
    for idx in range(offspring_crossover.shape[0]):
        # добавим рандомное число в ген
        random_value = np.random.uniform(-1.0, 1.0, 1)
        offspring_crossover[idx, 4] = offspring_crossover[idx, 4] + random_value
    return offspring_crossover

In [41]:
#количество повторений
num_generations = 5

#количество "родителей", которые участвуют в формировании новых ответов
num_parents_mating = 4

for generation in range(num_generations):
    # Подсчиываем "подходящесть"
    fitness = cal_pop_fitness(equation_inputs, new_population)
    # выбираем лучших родителей.
    parents = select_mating_pool(new_population, fitness, 
                                   num_parents_mating)

    # генерируем новый ответ
    offspring_crossover = crossover(parents,
                                    offspring_size=(pop_size[0]-parents.shape[0], num_weights))

    # добавляем "мутацию" (случайное смещение).
    offspring_mutation = mutation(offspring_crossover)
    new_population[0:parents.shape[0], :] = parents
    new_population[parents.shape[0]:, :] = offspring_mutation
    print("Generation ", generation)
    print("Fitness")
    print(fitness)
    print('Parents')
    print(parents)
    print('Mutation')
    print(offspring_mutation)
    print("Best fitness ", np.max(fitness))
    print('-------------------------------------------------------------')

TypeError: only size-1 arrays can be converted to Python scalars